-- MySQL Script generated by MySQL Workbench
-- Tue Jan  8 00:11:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mycartdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mycartdb` ;

-- -----------------------------------------------------
-- Schema mycartdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mycartdb` DEFAULT CHARACTER SET utf8 ;
USE `mycartdb` ;

-- -----------------------------------------------------
-- Table `mycartdb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mycartdb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mycartdb`.`categories` (
  `categoryID` INT(11) NOT NULL,
  `categoryTitle` VARCHAR(45) NULL DEFAULT NULL,
  `categoryDesc` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mycartdb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mycartdb`.`products` ;

CREATE TABLE IF NOT EXISTS `mycartdb`.`products` (
  `id` INT(11) NOT NULL,
  `prodName` VARCHAR(45) NULL DEFAULT NULL,
  `prodDesc` LONGTEXT NULL DEFAULT NULL,
  `prodCategory` VARCHAR(45) NULL DEFAULT NULL,
  `prodStock` VARCHAR(45) NULL DEFAULT NULL,
  `prodImageLink` VARCHAR(45) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_table2`
    FOREIGN KEY (`id`)
    REFERENCES `mycartdb`.`categories` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SELECT SLEEP(2); 

insert into categories (categoryID, categoryTitle, categoryDesc) values('1', 'Gadgets', 'Smart Watches, Smart Bands, IoT Devices');
insert into categories (categoryID, categoryTitle, categoryDesc) values('2', 'Clothes', 'Tshirts, Jeans, Shoes, Handbags');
insert into categories (categoryID, categoryTitle, categoryDesc) values('3', 'Smartphones', 'Apple, Samsung, Huawei, Xiaomi, Asus');
insert into categories (categoryID, categoryTitle, categoryDesc) values('4', 'Books', 'Fantasy, Cooking, DIY, Sciences, History');
insert into categories (categoryID, categoryTitle, categoryDesc) values('5', 'Music', 'Pop, Rock, Jazz, Blues, Techno');


SELECT SLEEP(2); 

INSERT INTO `products` (`id`,`prodName`,`prodDesc`,`prodCategory`,`prodStock`,`prodImageLink`,`price`) VALUES (1,'Arabella Women\'s Open Cardigan','96% Rayon, 4% Spandex, Imported, Machine WashbThis long-sleeve open-front sweater is draped from soft jersey and features an asymmetrical hem for a flowy fit','2','89','81v1G8y5MQL.jpg',11.99);
INSERT INTO `products` (`id`,`prodName`,`prodDesc`,`prodCategory`,`prodStock`,`prodImageLink`,`price`) VALUES (2,'Xiaomi Mi Band 3 Fitness Tracker','Real-time Display of Exercise Duration, Mileage, Heart Rate, etc., 50 meters Swimming Waterproof. All-Day Health Management More accurate pedometer, heart rate, sleep quality monitoring, sedentary reminder\r Reject Call without Phone The brand new millet bracelet 3 can also display the caller name or number if you do not want to answer.','1','16','71ZIrJ6XLLL.jpg',34.33);
INSERT INTO `products` (`id`,`prodName`,`prodDesc`,`prodCategory`,`prodStock`,`prodImageLink`,`price`) VALUES (3,'Brown Bear, Brown Bear, What Do You See?','These beloved children\'s stories are now available in beginning reader format. Complete with an introduction by master educator Laura Robb, and with fun reading activities added, these new versions of Brown Bear, Brown Bear, What Do You See? and Polar Bear, Polar Bear, What Do You Hear? are certain to appeal to a new age group and find an even wider audience. ','5','55','61qpAauXzIL.jpg',4.93);
